run:
  deadline: 5m

linters:
  enable:
    - deadcode
    - govet
    - ineffassign
    - interfacer
    - maligned
    - megacheck
    - structcheck
    - unconvert
    - varcheck
  enable-all: false
  disable-all: true
#  presets:
#    - bugs
#    - unused
  fast: false
