version: 2

project_name: filebrowser

env:
  - GO111MODULE=on

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/filebrowser/filebrowser/v2/version.Version={{ .Version }} -X github.com/filebrowser/filebrowser/v2/version.CommitSHA={{ .ShortCommit }}
    main: main.go
    binary: filebrowser
    goos:
      - darwin
      - linux
      - windows
      - freebsd
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
      - riscv64
    goarm:
      - "5"
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: freebsd
        goarch: arm

archives:
  - name_template: "{{.Os}}-{{.Arch}}{{if .Arm}}v{{.Arm}}{{end}}-{{ .ProjectName }}"
    formats: ["tar.gz"]
    format_overrides:
      - goos: windows
        formats: ["zip"]

dockers_v2:
  - id: filebrowser
    images:
      - "filebrowser/filebrowser"
    dockerfile: Dockerfile
    tags:
      - "latest"
      - "{{ .Tag }}"
      - "v{{ .Major }}"
    labels:
      org.opencontainers.image.created: "{{.Date}}"
      org.opencontainers.image.name: "{{.ProjectName}}"
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.version: "{{.Version}}"
      org.opencontainers.image.source: "{{.GitURL}}"
    extra_files:
      - docker
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm/v6
      - linux/arm/v7
  - id: filebrowser-s6
    images:
      - "filebrowser/filebrowser"
    dockerfile: Dockerfile.s6
    tags:
      - "s6"
      - "{{ .Tag }}-s6"
      - "v{{ .Major }}-s6"
    labels:
      org.opencontainers.image.created: "{{.Date}}"
      org.opencontainers.image.name: "{{.ProjectName}}"
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.version: "{{.Version}}"
      org.opencontainers.image.source: "{{.GitURL}}"
    extra_files:
      - docker
    platforms:
      - linux/amd64
      - linux/arm64

homebrew_casks:
  - name: filebrowser
    repository:
      owner: filebrowser
      name: homebrew-tap
    commit_author:
      name: FileBrowser Robot
      email: robot@filebrowser.org
    homepage: https://github.com/filebrowser/filebrowser
    description: File Browser is a create-your-own-cloud-kind of software where you can install it on a server, direct it to a path and then access your files through a nice web interface
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/filebrowser"]
          end
