build:
  main: cmd/filemanager/main.go
  binary: filemanager
  goos:
    - darwin
    - linux
    - windows
    - freebsd
    - netbsd
    - openbsd
  goarch:
    - amd64
    - 386
    - arm
    - arm64
  ignore:
    - goos: openbsd
      goarch: arm
      goarm: 6
    - goos: freebsd
      goarch: arm
      goarm: 6

archive:
  name_template: "{{.Os}}-{{.Arch}}-{{ .ProjectName }}"
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
