build:
  main: cmd/filebrowser/main.go
  binary: filebrowser
  goos:
    - darwin
    - linux
    - windows
    - freebsd
    - netbsd
    - openbsd
    - dragonfly
    - solaris
  goarch:
    - amd64
    - 386
    - arm
    - arm64
    - mips
    - mips64
    - mipsle
    - mips64le
  ignore:
    - goos: openbsd
      goarch: arm
      goarm: 6
    - goos: freebsd
      goarch: arm
      goarm: 6
    - goos: linux
      goarch: arm64

archive:
  name_template: "{{.Os}}-{{.Arch}}-{{ .ProjectName }}"
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
