FROM ghcr.io/linuxserver/baseimage-alpine:arm32v7-3.17

RUN apk --update add ca-certificates \
                     mailcap \
                     curl

HEALTHCHECK --start-period=2s --interval=5s --timeout=3s \
  CMD curl -f http://localhost/health || exit 1

# copy local files
COPY docker/root/ /
COPY filebrowser /usr/bin/filebrowser

# ports and volumes
VOLUME /srv /config /database
EXPOSE 80