#!/usr/bin/with-contenv bash

# Ensure configuration exists
if [ ! -f "/config/settings.json" ]; then
  cp -a /defaults/settings.json /config/settings.json
fi

# permissions
chown abc:abc \
	/config/settings.json \
	/database \
	/srv
