#!/usr/bin/with-contenv bash

# copy config
if [ ! -f "/config/settings.json" ]; then
  cp -a /defaults/settings.json /config/settings.json
fi

# check if db exists
if [ ! -f "/database/filebrowser.db" ]; then
  touch "/database/filebrowser.db"
fi

# permissions
chown -R "$PUID:$PGID" \
	/config \
	/database \
	/srv
