package cnc

import (
	"os"
	"path/filepath"
	"testing"
)

func writeTempNc(t *testing.T, body string) string {
	t.Helper()
	dir := t.TempDir()
	p := filepath.Join(dir, "test.nc")
	if err := os.WriteFile(p, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
	return p
}

func TestBuildChaptersDropsPreambleAndKeepsOperationHeaders(t *testing.T) {
	body := `(GENERATED BY FUSION 360 - HAAS)
(DATE 2026-05-11 14:22:00)
(T5 D=0.5 - bullnose)
(T7 D=0.25 - drill)
G90 G54
(OP1: ROUGH XY)
G0 X0 Y0
G1 Z-0.1 F10
(OP2: FINISH XY)
G1 X1.0
M30
`
	p := writeTempNc(t, body)
	out, err := BuildChapters(p, "/test.nc")
	if err != nil {
		t.Fatal(err)
	}
	if out.Total != 2 {
		t.Fatalf("expected 2 chapters, got %d (%+v)", out.Total, out.Chapters)
	}
	if out.Chapters[0].Comment != "OP1: ROUGH XY" {
		t.Fatalf("first chapter wrong: %+v", out.Chapters[0])
	}
	if out.Chapters[1].Comment != "OP2: FINISH XY" {
		t.Fatalf("second chapter wrong: %+v", out.Chapters[1])
	}
	// Lines are 1-based.
	if out.Chapters[0].Line != 6 {
		t.Fatalf("expected line 6, got %d", out.Chapters[0].Line)
	}
}

func TestBuildChaptersIgnoresInlineComments(t *testing.T) {
	body := `G90
(REAL CHAPTER)
G1 X1.0 Y2.0 (inline note — must not become a chapter)
G1 X2.0
`
	p := writeTempNc(t, body)
	out, _ := BuildChapters(p, "/x")
	if out.Total != 1 || out.Chapters[0].Comment != "REAL CHAPTER" {
		t.Fatalf("inline comment leaked: %+v", out.Chapters)
	}
}

func TestBuildChaptersSemicolonStyle(t *testing.T) {
	body := `G90
; Operation 1: Face mill
G0 X0 Y0
; Operation 2: Pocket
G1 X1.0
`
	p := writeTempNc(t, body)
	out, _ := BuildChapters(p, "/x")
	if out.Total != 2 {
		t.Fatalf("expected 2 chapters, got %+v", out.Chapters)
	}
	if out.Chapters[0].Comment != "Operation 1: Face mill" {
		t.Fatalf("first wrong: %+v", out.Chapters[0])
	}
}

func TestBuildChaptersHandlesEmptyFile(t *testing.T) {
	p := writeTempNc(t, "")
	out, err := BuildChapters(p, "/x")
	if err != nil {
		t.Fatal(err)
	}
	if out.Total != 0 {
		t.Fatalf("expected 0 chapters, got %+v", out)
	}
}

func TestBuildChaptersAllPreamble(t *testing.T) {
	// File never gets to a G-code line — every comment is preamble.
	body := `(DATE 2026-05-11)
(T1)
(T2)
`
	p := writeTempNc(t, body)
	out, _ := BuildChapters(p, "/x")
	if out.Total != 0 {
		t.Fatalf("all-preamble file should yield zero chapters, got %+v", out.Chapters)
	}
}

func TestChapterAtBinarySearch(t *testing.T) {
	chapters := []Chapter{
		{Line: 10, Comment: "OP1"},
		{Line: 50, Comment: "OP2"},
		{Line: 100, Comment: "OP3"},
	}
	cases := []struct {
		at   int
		want string
	}{
		{5, ""},
		{10, "OP1"},
		{25, "OP1"},
		{50, "OP2"},
		{99, "OP2"},
		{100, "OP3"},
		{99999, "OP3"},
	}
	for _, c := range cases {
		got := ChapterAt(chapters, c.at)
		if c.want == "" {
			if got != nil {
				t.Errorf("at=%d: expected nil, got %+v", c.at, got)
			}
			continue
		}
		if got == nil || got.Comment != c.want {
			t.Errorf("at=%d: expected %q, got %+v", c.at, c.want, got)
		}
	}
}

func TestChapterAtEmpty(t *testing.T) {
	if got := ChapterAt(nil, 10); got != nil {
		t.Fatalf("nil list should return nil, got %+v", got)
	}
	if got := ChapterAt([]Chapter{}, 10); got != nil {
		t.Fatalf("empty list should return nil, got %+v", got)
	}
}
